// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuangKuApi.Data;

#nullable disable

namespace RuangKuApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215201651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("RuangKuApi.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalKembali")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");
                });
#pragma warning restore 612, 618
        }
    }
}
